name: Manage K8sGateway Org
on:
  push:
    branches:
    - main
    paths:
    - org.yaml
jobs:
  manage-org:
    runs-on: ubuntu-latest
    steps:
    - name: checkout community repo
      uses: actions/checkout@v4
    - name: update org
      env:
        GH_TOK: ${{secrets.GATEWAYBOT}}
      run: |
        echo $GH_TOK >> ./GH_TOK
        script/org/update.sh --confirm
        rm ./GH_TOK
